micronaut:
  application:
    name: lista
datasources:
  default:
    url: jdbc:h2:./zaps-list;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: create
    dialect: H2

jackson:
  serializationInclusion: NON_NULL # Não permite que objetos nulos sejam retornados em JSON output
  bean-introspection-module: true
  alwaysSerializeErrorsAsList: true
  serialization:
    writeDatesAsTimestamps: false
